trigger:
- develop

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildApps
  jobs:
  - job: BuildGradleProject
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: 'app/webui/'
        tasks: 'build'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
    - task: CmdLine@2
      inputs:
        script: ls -alh dist/
