pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildApps
  jobs:
  - job: BuildWebuiApp
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'app/webui/gradlew'
        workingDirectory: 'app/webui/'
        tasks: 'build'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false

  - job: BuildWorkerApp
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          addToPath: true
          architecture: 'x64'
      - task: PythonScript@0
        inputs:
          scriptSource: 'inline'
          script: |
            pip install pipenv
            pipenv --python 3.8
            pipenv lock && \
              PIP_USER=1 \
              PIP_IGNORE_INSTALLED=1 \
              PIPENV_VENV_IN_PROJECT=1 \
              pipenv install -d
          workingDirectory: 'app/worker/'

    
