apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: hasher
  template:
    metadata:
      labels:
        component: hasher
    spec:
      hostname: hasher
      containers:
        - name: hasher
          image: dafespinelsa/hasher:1.0-6228e7
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
