apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: rng
  template:
    metadata:
      labels:
        component: rng
    spec:
      hostname: rng
      containers:
        - name: rng
          image: dafespinelsa/rng:1.0-6228e7
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10