apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  namespace: docker-coins
spec:
  replicas: 3
  selector:
    matchLabels:
      component: webui
  template:
    metadata:
      labels:
        component: webui
    spec:
      hostname: webui
      containers:
        - name: webui
          image: dafespinelsa/webui:1.0
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
