version: '3'
services: 
    hasher:
        build:
            dockerfile: Dockerfile.dev
            context: ./hasher
    redis:
        image: 'redis:alpine'
    rng:
        build:
            dockerfile: Dockerfile.dev
            context: ./rng
    webui:
        build:
            dockerfile: Dockerfile.dev
            context: ./webui
        volumes:
            - /usr/src/app/node_modules
            - ./webui:/usr/src/app
        ports:
            - '8080:8080'
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
